name: next deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.15'

      - name: Set up yarn with Taobao registry
        run: |
          yarn config set registry https://registry.npmmirror.com
          yarn config set sass_binary_site https://npm.taobao.org/mirrors/node-sass/

      - name: Install dependencies with yarn
        run: yarn

      - name: Build Next.js project
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:.next/standalone